// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_system;

#nullable disable

namespace University_system.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20260705080013_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursescourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsstusentId")
                        .HasColumnType("int");

                    b.HasKey("CoursescourseId", "StudentsstusentId");

                    b.HasIndex("StudentsstusentId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("University_system.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<string>("courseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("courseTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("creditHours")
                        .HasColumnType("int");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<int?>("instructorId")
                        .HasColumnType("int");

                    b.Property<string>("semesterOffered")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("courseId");

                    b.HasIndex("departmentId");

                    b.HasIndex("instructorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("University_system.Models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("building")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("headOfInstructorId")
                        .HasColumnType("int");

                    b.HasKey("departmentId");

                    b.HasIndex("headOfInstructorId")
                        .IsUnique()
                        .HasFilter("[headOfInstructorId] IS NOT NULL");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("University_system.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("finalGrade")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("University_system.Models.Instructor", b =>
                {
                    b.Property<int>("instructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("instructorId"));

                    b.Property<string>("academicTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("hireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("instructorId1")
                        .HasColumnType("int");

                    b.Property<string>("officeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("instructorId");

                    b.HasIndex("instructorId1");

                    b.ToTable("instructors");
                });

            modelBuilder.Entity("University_system.Models.Student", b =>
                {
                    b.Property<int>("stusentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stusentId"));

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("enrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("gpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("stusentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("University_system.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursescourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_system.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsstusentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("University_system.Models.Course", b =>
                {
                    b.HasOne("University_system.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_system.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("instructorId");

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("University_system.Models.Department", b =>
                {
                    b.HasOne("University_system.Models.Instructor", "Instructor")
                        .WithOne("Department")
                        .HasForeignKey("University_system.Models.Department", "headOfInstructorId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("University_system.Models.Enrollment", b =>
                {
                    b.HasOne("University_system.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_system.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University_system.Models.Instructor", b =>
                {
                    b.HasOne("University_system.Models.Instructor", null)
                        .WithMany("Instructors")
                        .HasForeignKey("instructorId1");
                });

            modelBuilder.Entity("University_system.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("University_system.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("University_system.Models.Instructor", b =>
                {
                    b.Navigation("Department")
                        .IsRequired();

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("University_system.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
